async_eval_gpus: null
checkpoint:
  continue_training_from_init: false
  dump:
    every: 500
    keep: 0
  eval:
    every: 500
    keep: 0
  init_ckpt_path: null
  path: null
  s3_profile: null
data:
  add_bos: true
  add_eos: true
  add_patches: true
  arrow_batch_size: 100
  batch_size: 16
  buffer_size: 16
  dataset_files: null
  enable_byte_ngrams: false
  entropy_model_name: null
  file_format: arrow
  load_async: true
  max_encoder_seq_length: 12288
  pad_to_max_length: true
  patcher_args:
    device: cuda
    entropy_model_checkpoint_dir: null
    log_time: false
    max_patch_length: 16
    monotonicity: false
    patch_size: null
    patching_batch_size: 1
    patching_device: cuda
    patching_mode: !!python/object/apply:patching.PatchingModeEnum
    - entropy
    realtime_patching: false
    threshold: 1.2
    threshold_add: null
  prefetch_size: 64
  preprocess_dir: null
  root_dir: ./outputs
  s3_profile: null
  seed: 42
  seq_len: 8192
  sources:
    train:
      entropies_validation.arrow: 1
    validation:
      entropies_validation.arrow: 1
  tokenizer_args:
    init_kwargs:
      add_bos: false
      add_eos: false
    name: blt
debug_dynamo: false
dump_dir: ''
entropy_model: null
eval: null
eval_on_gpus: null
gc_collect_freq: 1000
grad_acc_steps: 16
max_steps: 4500
model:
  alpha_depth: disabled
  architecture: vanilla
  attn_bias_type: causal
  attn_impl: xformers
  attn_to_keep: all
  conv_kernel_size: null
  cross_attn_all_layers_decoder: true
  cross_attn_all_layers_encoder: true
  cross_attn_decoder: true
  cross_attn_encoder: true
  cross_attn_init_by_pooling: true
  cross_attn_k: 2
  cross_attn_nheads: 4
  cross_attn_use_flex_attention: true
  cross_attn_window_decoder: null
  cross_attn_window_encoder: null
  custom_bwd: false
  dim: 1024
  dim_global: 1024
  dim_local_decoder: 256
  dim_local_encoder: 256
  dim_patch_emb: null
  dim_token: null
  dim_token_emb: null
  downsampling_by_pooling: max
  dropout: 0
  encoder_enable_byte_group_hash: true
  encoder_enable_byte_ngrams: true
  encoder_hash_byte_group_nb_functions: 4
  encoder_hash_byte_group_size:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  encoder_hash_byte_group_vocab: 100000
  encoder_lm_loss: false
  encoder_ngram_table_dir: null
  encoder_ngram_to_size_str: 3:16666,4:16666,5:16666,6:16666,7:16666,8:16666
  encoder_preds_low_entropy_toks: null
  encoder_preds_random_toks: null
  entropy_model_checkpoint_dir: null
  entropy_model_is_ngram_model: false
  eos_id: 2
  ffn_dim_multiplier: 2.5
  full_logging_n_layers: 4
  fuse_sequence_parallel: false
  global_local_decoder_residual_layer: null
  head_dim: null
  init_base_std: null
  init_std_factor: disabled
  init_use_depth: current
  init_use_gaussian: true
  layer_ckpt: all
  local_attention_window_len: 512
  log_patch_lengths: false
  loss_parallel: false
  max_encoder_seq_length: 8192
  max_length: 8192
  max_patch_length: 16
  max_seqlen: 1024
  monotonicity: false
  multiple_of: 256
  n_heads: 8
  n_heads_global: 8
  n_heads_local_decoder: 4
  n_heads_local_encoder: 4
  n_kv_heads: null
  n_kv_heads_global: null
  n_layers: 8
  n_layers_global: 8
  n_layers_local_decoder: 5
  n_layers_local_encoder: 1
  ngram_vocab_sizes: 1
  non_linearity: swiglu
  norm_affine: true
  norm_eps: 1.0e-05
  norm_type: rmsnorm
  output_size: -1
  pad_to_max_length: false
  patch_in_forward: false
  patch_size: null
  patching_batch_size: 1
  patching_device: cuda
  patching_mode: entropy
  patching_threshold: 1.2
  patching_threshold_add: null
  patching_thresholds_str: null
  pm_size: 0
  pre_norm: true
  recompute_attn: true
  recompute_fc1_out: false
  recompute_fc3_out: false
  rope_theta: 10000.0
  rope_use_fp32_in_outer_product: false
  seed: 42
  sequence_parallel: false
  share_encoder_decoder_emb: false
  tie_local_encoder_decoder: false
  tie_local_encoder_decoder_logits: false
  tokenize_with_bpe_delimiter: false
  use_fsdp: false
  use_local_encoder_transformer: true
  use_rope: true
  vocab_size: 256
  weight_tying: false
name: lingua
optim:
  annealing_step: 1000
  beta1: 0.9
  beta2: 0.95
  clip: 1.0
  cosine_theta: 1.0
  cycle_length: 1.0
  decay_fraction: 0.1
  epsilon: 1.0e-08
  exp_factor: 0.5
  lr: 0.0008
  lr_min_ratio: 0.1
  scheduler: cosine
  warmup: 45
  weight_decay: 0.1
probe_freq: null
seed: 42
steps: 4500
train_entropy_model: false
